# Generated by Django 6.0.2 on 2026-02-14 15:49

import ClientApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un client avec cet email existe déjà.'}, max_length=254, unique=True, validators=[ClientApp.models.validate_gmail]),
        ),
    ]
