# Generated by Django 6.0.2 on 2026-02-14 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(error_messages={'max_length': 'Le nom de la catégorie doit contenir entre 10 et 100 caractères.', 'unique': 'Une catégorie avec ce nom existe déjà.'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Le nom de la catégorie doit contenir entre 10 et 100 caractères.')]),
        ),
    ]
