# Generated by Django 6.0.2 on 2026-02-14 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de la chambre n'est pas valide.", regex='^Room[a-zA-Z]\\d+$')]),
        ),
    ]
